name: on push (branches)

on: 
  push:
    branches:
      - main
      - 'release/**'
    paths:
      - 'sample-app/**'
      - '**.js

jobs:
  filtered-build:
    runs-on: ubuntu-latest
    steps:
      -name: this is the only runs for te branches/path above
       run: echo "Relevant chnage detected on branch"
