name: checkout

on: workflow_dispatch

jobs:
  withoutcheckout:
    runs-on: ubuntu-latest
    steps:
       -name: try to list the files
        run: ls-la
  with-checkout:
    runs-on: ubuntu-latest
    steps:
       -name: check the code
        uses: actions/checkout@v5

      -name: list the files
       run: ls -la
