name: 01 -Hello world

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello, Github actions"

      - name: Print multiple lines
        run: |
           echo "This is an steps run several commands."
           echo "today's runner is : $RUNNER_OS"
           echo "The repo is : $GITHUB_REPOSITORY"
